### ISSUE TITLE
qFlipper needs SD-card too ?

### ISSUE THREAD

**Issue by the-Arioch** [Slipn3r/flipper-webusb-upgrade#25]
When Windows 7 desktop user enters update site he is presented with a juxtapposition - yse Windows app or Android app.

Android app then lists the EXTR requirement that tells it appart from qFlipper: the need for an SD-card.

But okay, i can do without Android app, so i run qFlipper...

...and have a very unpleasant surprise it would not work without SD-card too.

----

Please, spell the requirements upfront, so not bad surprises wuould be met.
If ALL the update avenues require SD card with NN MB free space - warn user in advance and explicitly.

The qurrent structure of the sites lists SD-card requirement specifically as a quirk of Anndroid applicaiton, telling it from other upgrade methods, which is wrong.

**Comment by gsurkov** [comment]
It is possible to update via qFlipper without an SD-card (although not recommended). 

Press the "Install" or "Update" button and when the message saying that an SD card is needed pops up, press and hold the Alt key. The "Ok" button will change to "Force install", so press it and it will do just that.

**Comment by the-Arioch** [comment]
Well, you have to make a decision what is normal operation and what is "last resort" better kept away from 99% of users.

The former has to be explicitly and in advance communicated. The latter left to some deeply hidden fineprint :-)

Since this alt-trick is not readily advertized, it clearly is not intended for wider use. However if this decision be changed, then this wold had to be publ;ished on the web-page.
